config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  get 'home', to: 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'
  root 'static_pages#home'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_alerts.html.slim
= turbo_frame_tag 'alerts'
  - flash.each do |msg_type, msg|
    div(class="alert #{msg_type}")= msg

app/views/layouts/_header.slim
header
  nav
    ul
      li= link_to 'Home', home_path
      li= link_to 'Help', help_path
      li= link_to 'About', about_path
      li= link_to 'Contact', contact_path
      - if logged_in?
        li= link_to 'Users', users_path
        li= link_to 'Profile', user_path(current_user)
        li= link_to 'Settings', edit_user_path(current_user)
        li= link_to 'Log out', logout_path, data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' }
      - else
        li= link_to 'Log in', login_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = yield(:title) + ' | Ruby on Rails Tutorial Sample App'

    meta name="viewport" content="width=device-width,initial-scale=1"

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = stylesheet_link_tag 'https://cdn.jsdelivr.net/npm/water.css@2/out/water.css'
    = javascript_importmap_tags

  body
    = render 'layouts/header'
    = render 'layouts/alerts'

    = yield

    - if Rails.env.development?
      div
        = debug(params)